steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - 'gcr.io/entrenamiento1/hello-world:latest'
    - -f
    - './workspace/Dockerfile' 
    - . 
options:
  logging: CLOUD_LOGGING_ONLY
images: ['gcr.io/entrenamiento1/hello-world:latest']