steps:
  # Paso 1: Instalar dependencias (opcional)
  - name: 'gcr.io/cloud-builders/npm:1.10.1'
    args: ['install']
    dir: 'src'

  # Paso 2: Ejecutar pruebas (opcional)
  - name: 'gcr.io/cloud-builders/npm:1.10.1'
    entrypoint: 'npm'
    args: ['test']
    dir: 'src'

  # Paso 3: Empaquetar la aplicación (si aplica)
  - name: 'gcr.io/cloud-builders/npm:1.10.1'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'src'

  # Paso 4: Desplegar en Google App Engine
  - name: 'gcr.io/cloud-builders/npm:1.10.1'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']
    dir: 'src'

# Configurar opciones de compilación
options:
  logging: CLOUD_LOGGING_ONLY  # Los logs se almacenan solo en Cloud Logging
